use_frameworks!

platform :ios, '9.0'

target 'AdMopubSDK_Example' do
  pod 'AdMopubSDK', :path => '../'

  target 'AdMopubSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
